######################################################################
# Automatically generated by qmake (2.01a) Fri May 29 11:56:09 2009
######################################################################

TEMPLATE = app
TARGET = testrssdocument
DEPENDPATH += .
INCLUDEPATH += .
QT += xml network webkit

# Input
HEADERS += wget.h rsschannel.h rssdocument.h
SOURCES += wget.cpp rsschannel.cpp rssdocument.cpp main.cpp
