######################################################################
# Automatically generated by qmake (2.01a) Fri May 29 11:56:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml network

# Input
HEADERS += httpget.h rsschannel.h rssdocument.h
SOURCES += httpget.cpp rsschannel.cpp rssdocument.cpp main.cpp
